[package]
name = "indexgen"
version = "0.1.0"
authors = ["Amandus Thorsrud <ama.thorsrud@gmail.com>"]

[dependencies]
handlebars = "0.32.1"
serde = "1.0.47"
serde_derive = "1.0.47"
serde_json = "1.0.17"
